version: "3"

services:
  dupyter:
    image: matsuura0831/dupyter
    volumes:
      - "${PWD}:/workspace"
    environment:
      - AUTH=1
    ports:
      - "8888:8888"
    command: "/entrypoint.sh"

